### ISSUE TITLE
Unable to connect to AWS from juypter Notebook after spinning up glue_libs_1.0.0_image_01 image 

### ISSUE THREAD

**Issue by purnima1612** [awslabs/aws-glue-libs#136]
```
version: "2"

services:
 awsglueservice:
  image: awsglue
  build: ./spark
  container_name: awsglue-container
  hostname: localhost
  ports:
   - "8888:8888"
   - "4040:4040"
  env_file: 
   - ./env/spark-env-vars.env
  command : "/home/jupyter/jupyter_start.sh"
  volumes:
   - ~/.aws:/root/.aws:ro
   - ../app/jupyter_workspace:/home/jupyter/jupyter_default_dir
   

```

Once docker spins up and  I run interactive bash shell inside the docker there on running following command 
aws sts get-caller-identity | cat 

I can see aws user details 
But when I am creating juypter notebook and trying to run same command using boto3 I am getting following error :

 An error was encountered:
An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.

After that I tried to access S3 bucket from docker bash . It was able to connect  but again from notebook getting 403  access denied error
